### ISSUE TITLE
add visual descriptions

### ISSUE THREAD

**Issue by tgoslee** [Terra-Foundation-for-American-Art/Artnav#1]
Inside of the setting tab on a piece of artwork, add an input so a description can be added. Display that description when the discover button is clicked. The description should go under the title and artist name. 

<img width="794" alt="Screenshot 2023-08-08 at 6 47 57 PM" src="https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/06de3af8-ae01-4fb2-8bcf-37d3bc32ecc9">
<img width="513" alt="Screenshot 2023-08-08 at 6 47 47 PM" src="https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/9fb05645-292a-4ff6-9bc6-6e6689736067">

**Comment by je321ss** [comment]
@tgoslee It looks like there's an issue for published Artnavs.

For works that are live on the Artnav site, the backend preview of the "i" button has code visible in the new image description section:
![backend](https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/10855038/2819fb35-ffc9-4d68-935f-4d7000d54ae9)

For works that are live on the Artnav site, the front end does not show anything now when you click the "i" button:
 ![frontend](https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/10855038/cb1fc502-3795-4cca-ab82-5867e4a12d05)

**Comment by tgoslee** [comment]
@je321ss I just made an update to correct this issue. Test it out and let me know if its working. 
![Screenshot 2023-08-23 at 12 07 37 PM](https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/947d9ae9-b6cc-4594-b264-a3d58aad86aa)
![Screenshot 2023-08-23 at 12 07 18 PM](https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/b5d54c8c-043c-4118-8d25-c08b4b46a683)

**Comment by je321ss** [comment]
@tgoslee When I click the "i" on the live site (not logged in), it just turns into an "x" and doesn't have show any of the tombstone info (nothing pops up).

**Comment by tgoslee** [comment]
@je321ss what live site are you referring to? I am going to https://artnav.terraamericanart.org/ and logging in. I don't have a way to view it without logging in.

**Comment by je321ss** [comment]
https://www.terraamericanart.org/what-we-offer/our-art-collection/artnav/ 

This is how the public accesses the site. You can click on each image or link under the accordions to see the published artnavs. Sorry we didn't send you this path before!!

**Comment by tgoslee** [comment]
I believe i fixed it!
![Screenshot 2023-08-23 at 12 07 18 PM](https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/bb963e7b-cd8a-42d5-a96d-dbc69f2da6bf)

**Comment by tgoslee** [comment]
I believe it is fixed now.
<img width="759" alt="Screenshot 2023-08-24 at 2 36 21 PM" src="https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/62fd0779-e98e-4e25-bb01-b724f6decfe5">

**Comment by je321ss** [comment]
Looks good!
