### ISSUE TITLE
add alt text 

### ISSUE THREAD

**Issue by tgoslee** [Terra-Foundation-for-American-Art/Artnav#2]
Add an input for alt text under artwork details. Create a small box in the bottom corner of the artwork that displays ALT. When the user hovers over the box it will display the alt text for the image. 
<img width="794" alt="Screenshot 2023-08-08 at 6 47 57 PM" src="https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/8a8f05fd-b43e-428d-afb2-108689ea8427">

**Comment by t4ylorlpoulin** [comment]
@tgoslee Super, thank you so much. I experimented with this and it seems like any amount of text can be added even though it's just one line for entry -- is there a limit that you included, or are there unlimited lines? Some of these image descriptions may consist of a long paragraph or so.

I also wonder if there can be a bit more space -- like a full line -- between the artist's name and the text. Can the image description text also begin automatically with the words **Image Description:** ... ? Let us know if these things may be possible. Thank you!

**Comment by tgoslee** [comment]
I can place a limit but if you want it to be unlimited it can be... up to you all. I can add space between the artist's name and the image description. Also, you would like it to look like

By Trenisha Goslee

Image Description: A developer coding on the computer

**Comment by tgoslee** [comment]
- I added a larger text area for the text description
- I added a space between the artist's name and the image description
- I added an Image Description at the start of the text

<img width="788" alt="Screenshot 2023-08-29 at 5 43 56 PM" src="https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/72071d81-5108-4369-8786-7051ad95e19d">
 
<img width="662" alt="Screenshot 2023-08-29 at 5 43 43 PM" src="https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/639fd155-0543-4d0d-8a0a-552b766f9bcc">

@t4ylorlpoulin

**Comment by t4ylorlpoulin** [comment]
@tgoslee this looks super! I think it would be great if the text box were unlimited for now. I think this issue can be closed. Thanks so much!
