### ISSUE TITLE
Categorization of ArtNav'd works

### ISSUE THREAD

**Issue by t4ylorlpoulin** [Terra-Foundation-for-American-Art/Artnav#6]
Please eliminate "Collections" function

For new categorization, can we have:
- "browse all" (or "see all")
- two filter/sorting options:
1. by date
2. by artist A-Z

Ideally we could see all/filter on both back end and front end. On front end, it will not look like much since there are currently only 12 public ArtNavs, but the functionality would be nice if it's possible, and it would be very useful on the back end as we build more content.

**Comment by t4ylorlpoulin** [comment]
Hi @tgoslee I checked through the site and still see the Collections tab in the nav bar (tho it is empty, so the Collections are indeed gone). The option to add a Collection also still appears in the Create form and in the Settings form (when you start typing in the box it prompts you to add a new collection). I cleared my cache to see if that was an issue and they still appeared.

**Comment by t4ylorlpoulin** [comment]
Hi @tgoslee this looks great, I'm no longer seeing the Collections tab or option anywhere. I think we can close this. Thanks!

**Comment by tgoslee** [comment]
@t4ylorlpoulin this still talks about sorting. Do you still want that implemented?

**Comment by t4ylorlpoulin** [comment]
@tgoslee yes please! If you're able to sort by the two methods mentioned above (and then also the option to "See all") that would be great.

**Comment by tgoslee** [comment]
I have added sorting by published, artist's last name, and the creation of the art map. This would close issues #4 and #6. 

Let me know what you think. @t4ylorlpoulin @je321ss 

![Screenshot 2023-08-31 at 2 14 33 PM](https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/f008df26-9ce3-4d0a-bda7-f029b349d24b)

**Comment by t4ylorlpoulin** [comment]
Thanks so much @tgoslee . Artist Name and Published look great. Does Sort by Date have other conditions attached to it, and is it in ascending order? Some of the dates start with "c." (c. 1898) but those are scattered throughout and not in ascending order. Ex: Boat Going through Inlet (c. 1929) has a "c" and so does Horse Drawn Cabs at Evening (c. 1890) but Boat Going Through Inlet appears first in the list and Horse Drawn Cabs is several lines down. I'm wondering if that's because Boat Going Through Inlet is published and Horse Drawn Cabs isn't. Some dates are also spans, like 1929-30, so that might also throw off the ascending order, I'm not sure.

**Comment by tgoslee** [comment]
The date is currently sorted by the date the artmap was created in the app. The dates it can be sorted by are last updated, the date it was created in the app, or the date the artwork was published. Which would you like to use? @t4ylorlpoulin

**Comment by t4ylorlpoulin** [comment]
Got it! Thanks @tgoslee Let's go with sort by last updated. I think that will be useful in the backend.

**Comment by tgoslee** [comment]
Okay @t4ylorlpoulin I just added the change. You should be able to see it live now.
