### ISSUE TITLE
"Related"

### ISSUE THREAD

**Issue by t4ylorlpoulin** [Terra-Foundation-for-American-Art/Artnav#7]
Currently "related" pulls in by "Collection". See issue #6, we would like to eliminate "Collection" as categorization. 

Can "related" be renamed to "More" and pull in any 3 public ArtNav pieces?

**Comment by tgoslee** [comment]
I added " View More: " under the artist's name and image description. It pulls three random published artmaps every time it's refreshed. It takes them to the gallery link. 

<img width="990" alt="Screenshot 2023-09-08 at 3 22 41 PM" src="https://github.com/Terra-Foundation-for-American-Art/Artnav/assets/60710670/786f1cc2-fe7c-4e34-9f43-96f946fcb1c2">

@t4ylorlpoulin

**Comment by t4ylorlpoulin** [comment]
@tgoslee this is SO beautiful! Thank you! This is exactly what we envisioned.

For the future, when we have more works completed, would it be possible to organize them in some way -- tagging them, for example, in the back end, so that we might push related works to each other? I don't think we're quite there yet with our content, so maybe this is a future/separate issue, but I'd be glad to know what you think.

**Comment by tgoslee** [comment]
Thank you. I'm glad you are happy with it. Yes, there is a way to do this. You would have to think about how they would be organized. By theme, by artist, by time period, etc
